#pragma once
#include <pane/co_init.hpp>
#include <pane/color.hpp>
#include <pane/config.hpp>
#include <pane/console.hpp>
#include <pane/error.hpp>
#include <pane/file_picker.hpp>
#include <pane/filesystem.hpp>
#include <pane/gdi_plus.hpp>
#include <pane/glaze.hpp>
#include <pane/guid.hpp>
#include <pane/input.hpp>
#include <pane/math.hpp>
#include <pane/message_window.hpp>
#include <pane/print.hpp>
#include <pane/process.hpp>
#include <pane/system.hpp>
#include <pane/text.hpp>
#include <pane/url.hpp>
#include <pane/utility.hpp>
#include <pane/webview.hpp>
#include <pane/window.hpp>
