on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: repo

      - uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/repo/build/_deps
          key: deps-${{ hashFiles('repo/pane/libs/CMakeLists.txt') }}

      - run: |
          Set-Location ${{ github.workspace }}/repo
          cmake -S . -B build

      - uses: actions/upload-artifact@v4
        with:
          name: project-json
          path: ${{ github.workspace }}/repo/build/pane/generated/pane/project.json

  notify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: project-json

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/mthierman/mthierman.pages.dev/dispatches \
          --method POST \
          --input project.json
