on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: repo

      - uses: actions/checkout@v5
        with:
          repository: mthierman/powershell-scripts
          path: scripts

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - cwd: "repo"

      - uses: actions/setup-node@v5
        with:
          node-version: 22.20.0
          cache: pnpm
          cache-dependency-path: repo/pnpm-lock.yaml

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - uses: astral-sh/setup-uv@v7
        with:
          working-directory: repo
          python-version: 3.13
          enable-cache: true

      - run: |
          uv tool install gersemi

      - uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/repo/build/_deps
          key: deps-${{ hashFiles('repo/pane/libs/CMakeLists.txt') }}

      - run: |
          .\scripts\dev
          Set-Location ${{ github.workspace }}/repo
          cmake -S . -B build

      - uses: actions/upload-artifact@v4
        with:
          name: project-json
          path: ${{ github.workspace }}/repo/build/pane/generated/pane/project.json

  notify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: project-json

      - env:
          GITHUB_TOKEN: ${{ secrets.WEB }}
        run: |
          gh api repos/mthierman/mthierman.pages.dev/dispatches \
          --method POST \
          --input project.json
