on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          path: repo

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/repo/build/_deps
          key: deps-${{ hashFiles('repo/pane/libs/CMakeLists.txt') }}

      - name: CMake
        run: |
          Set-Location ${{ github.workspace }}/repo
          cmake -S . -B build

  notify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.WEBSITE }}
        run: |
          gh api repos/mthierman/mthierman.pages.dev/dispatches \
          --method POST \
          --input "${{ github.workspace }}/repo/build/pane/generated/pane/project.json"
