name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          path: "repo"

      - name: Checkout scripts
        uses: actions/checkout@v5
        with:
          repository: mthierman/powershell-scripts
          path: powershell-scripts

      - name: Checkout web
        uses: actions/checkout@v5
        with:
          repository: mthierman/mthierman.pages.dev
          path: "web"
          token: ${{ secrets.WEBSITE }}

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/repo/build/_deps
          key: deps-${{ hashFiles('repo/pane/libs/CMakeLists.txt') }}

      - name: CMake
        run: |
          .\powershell-scripts\dev.ps1
          Set-Location ${{ github.workspace }}\repo
          cmake --version
          cmake -S . -B build

      - name: Update website
        run: |
          Set-Location ${{ github.workspace }}\web
          Copy-Item "${{ github.workspace }}\repo\build\pane\generated\pane\project.json" -Destination "${{ github.workspace }}\web\src\content\projects\pane.json"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Pane: auto-commit'
          git push
