on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.WEB }}
        run: |
          gh api repos/mthierman/mthierman.pages.dev/dispatches \
          --method POST \
          --field event_type=pane-notify
