on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.WEBSITE }}
        run: |
          gh api repos/mthierman/mthierman.pages.dev/dispatches \
          --method POST \
          --field event_type=build-website
