on:
  workflow_dispatch:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 5

      - env:
          GH_TOKEN: ${{ secrets.WEB }}
        uses: mthierman/github-actions/notify-web@main
        with:
          name: "pane"
          version: "0.0.0"
          description: "C++ library for Windows"
          symbol: "🪟"
          repo: "https://github.com/mthierman/pane.git"
          releases: "https://github.com/mthierman/pane/releases"
          event_type: "pane-notify"
